### PR TITLE
Bumping airtable dependency to fix #62

### LINKED ISSUE #62: Update Airtable API Client to fix LoDash dependency
The version of the Airtable API client currently being used uses an old version of lodash which has a known security vulnerability. We should upgrade this repo to version [0.7.0](https://github.com/Airtable/airtable.js/releases/tag/v0.7.0) or greater to fix this.

Happy to make a PR updating the NPM package, but as I haven't contributed before, I wanted to drop an issue first and make sure it wasn't already a known issue. Thanks!

### PR DESCRIPTION
**Pull request by jamessimone**
@jbolda had a spare moment to take a look at this, all the tests are passing so I thought I would submit it!

### CODE REVIEW

**Comment by jbolda** [comment]
Thanks! It may be worth it long term to add the renovate bot to help keep this stuff up to date. And actually, GitHub Actions / CI + publish to npm might be worthwhile as well.

**Comment by jamessimone** [comment]
@jbolda rebasing to master re-started the review 😄 Thank you for approving this, though!

**Comment by jbolda** [comment]
Bah, lol... merging all of those PRs for the examples. Figured it was worth having those up to date for CI to run this on.

**Comment by jbolda** [comment]
Published in v2.0.9! Thanks again @jamessimone.

**Pull request merged**
