### PR TITLE
Use cleanKeys in Gatsby-land

### LINKED ISSUE #32: Mapping key clarifications
I've just run into an issue where my mappings where not correctly applying. I managed to try this down to me using the `cleanedKey` not the actual column name as is in Airtable.

Do you think this is a bug in the code and we should be using the `cleanedKey` here: https://github.com/jbolda/gatsby-source-airtable/blob/master/gatsby-node.js#L194

Or is this behavour expected? 

Happy to I open a PR to either fix the code or clarify that you need to use the actual column name within your `gatsby-config.js`?

### PR DESCRIPTION
**Pull request by jbolda**
This settles the API on using the `cleanKey` (that is, spaces removed from column name) everywhere. This includes in the `gatsby-config.js` (new) and in queries, etc. (previously in place).

This closes #32.

### CODE REVIEW

**Comment by shaunbent** [comment]
Hey @jbolda, sorry I've not replied to your questions for a while. I've been working on another project.

This PR looks good to me.

Will this result in a console warning every time a cleanedKey is used?

**Comment by jbolda** [comment]
This will only warn when the user puts in a key in `gatsby-config.js` that needs to be cleaned. The hope is the extra note in the readme is otherwise sufficient to key the user in to the fact that keys will be cleaned. This is less work, and we can always add more warning if we feel the need. How does the readme text addition sound?

**Comment by jbolda** [comment]
I wouldn't mind an extra set of eyes @eunjae-lee, if you have a free moment. I think I have the default values integrating in with the mapping / cleanKeys now.

**Comment by jbolda** [comment]
This appears to work in every repo that I have tried out. I am going to go ahead, merge and publish it.

**Pull request merged**
